nome=input('Qual é o seu nome? ')
idade=input('Qual a sua idade? ')
nascimento=input('Qual sua data de nascimento? (DD/MM/AA) ')
print('muito prazer,',nome)
print('você nasceu em {} portanto tem {} anos'.format(nascimento,idade))